### ISSUE TITLE
[Bug] v1.0.3 Not working at all.

### ISSUE THREAD

**Issue by AvocadoVR** [jsopn/vrc-lyrics#9]
![image](https://github.com/jsopn/vrc-lyrics/assets/135179467/6400a51e-eb29-4fa5-9644-59ed86e0f44f)
![image](https://github.com/jsopn/vrc-lyrics/assets/135179467/4b19d147-4171-47a5-a360-eb6f69de7816)

**Comment by jsopn** [comment]
Works for me. Have you updated the config.toml file? There's new params.
Also you should start playback after you launched the app, that's some Spotify restriction on websocket. Software cant see track that was playing before software was launched.

**Comment by jsopn** [comment]
Also please keep discussion of this issue here, not in the first one you created.

**Comment by AvocadoVR** [comment]
https://pastebin.com/LUpkA6Xw

This is my config.

**Comment by AvocadoVR** [comment]
![image](https://github.com/jsopn/vrc-lyrics/assets/135179467/6edce5bb-3ebe-406d-84a4-028e120ca2b7)

I was using the .exe Thats why it was giving me an issue.
